server:
  port: 3077

spring:
  application:
    name: trade-broker-service
  profiles:
    active: test
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



market:
  kafka:
    topic: market.tick