logging.config=classpath:logback1.xml

spring.application.name=trade-app
server.servlet.context-path=/broker
# Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tradding_db
spring.datasource.username=root
spring.datasource.password=ellenverma

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.main.log-startup-info=true
logging.config=classpath:logback.xml
logging.level.root=INFO
logging.level.org.springframework=INFO

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=renuaryanverma@gmail.com
spring.mail.password=xudj eccp clfq dzgr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


stock.selection.from.time.hour=9
stock.selection.from.time.minute=15
stock.selection.to.time.hour=9
stock.selection.to.time.minute=20

prev.stock.selection.from.time.hour=15
prev.stock.selection.from.time.minute=20
prev.stock.selection.to.time.hour=15
prev.stock.selection.to.time.minute=30


prev.super.selection.from.time.hour=14
prev.super.selection.from.time.minute=35
prev.super.selection.to.time.hour=15
prev.super.selection.to.time.minute=30



nifity50.candle.from.time.hour=9
nifity50.candle.from.time.minute=15
nifity50.candle.to.time.hour=9
nifity50.candle.to.time.minute=25


stock.entry.from.time.hour=9
stock.entry.from.time.minute=15
stock.entry.to.time.hour=9
stock.entry.to.time.minute=26

init.cron.expression=0/2 * * * * ?
regular.cron.expression=0/5 * * * * ?

atr.period=14
multiplier=3.0



